package com.example.productdetail.theme

import androidx.compose.ui.graphics.Color

val Vermilion = Color(0xFFD63F2F)
val OnVermilion = Color(0xFFFFFFFF)
val VermilionContainer = Color(0xFFFFE0DA)
val OnVermilionContainer = Color(0xFF4D1009)
val DeepNavy = Color(0xFF122A4F)
val OnDeepNavy = Color(0xFFFFFFFF)
val NavyContainer = Color(0xFFDCE6F7)
val OnNavyContainer = Color(0xFF071B38)
val EditorialGold = Color(0xFF8B5A00)
val OnEditorialGold = Color(0xFFFFFFFF)
val GoldContainer = Color(0xFFFFE6A6)
val OnGoldContainer = Color(0xFF2C1A00)
val EditorialCream = Color(0xFFF4EBDD)
val EditorialWhite = Color(0xFFFFFDF8)
val EditorialSurfaceVariant = Color(0xFFEAE0D4)
val Graphite = Color(0xFF211A17)
val MutedEspresso = Color(0xFF665A54)
val EditorialOutline = Color(0xFF88776D)
val EditorialOutlineVariant = Color(0xFFD8C9BE)
val Espresso = Color(0xFF2F201B)
val OnEspresso = Color(0xFFFFF3EA)

val VermilionDark = Color(0xFFFFB4A8)
val OnVermilionDark = Color(0xFF661107)
val VermilionContainerDark = Color(0xFF8C2116)
val OnVermilionContainerDark = Color(0xFFFFDAD4)
val DeepNavyDark = Color(0xFFB8C9EE)
val OnDeepNavyDark = Color(0xFF0A274E)
val NavyContainerDark = Color(0xFF29436B)
val OnNavyContainerDark = Color(0xFFDAE6FF)
val EditorialGoldDark = Color(0xFFF6C45C)
val OnEditorialGoldDark = Color(0xFF432C00)
val GoldContainerDark = Color(0xFF624200)
val OnGoldContainerDark = Color(0xFFFFE2A2)
val EditorialNight = Color(0xFF181310)
val EditorialSurfaceDark = Color(0xFF241C18)
val EditorialSurfaceVariantDark = Color(0xFF3A2E28)
val EditorialOnSurfaceDark = Color(0xFFF3E8E0)
val EditorialOnSurfaceVariantDark = Color(0xFFD8C7BD)
val EditorialOutlineDark = Color(0xFFA89488)
val EditorialOutlineVariantDark = Color(0xFF57473F)
