package com.example.burgerbuilder.theme

import androidx.compose.ui.graphics.Color

val DriveThruRed = Color(0xFFD9232E)
val OnDriveThruRed = Color(0xFFFFFFFF)
val DriveThruRedContainer = Color(0xFFFFDAD8)
val OnDriveThruRedContainer = Color(0xFF410007)
val GoldenMustard = Color(0xFF765A00)
val OnGoldenMustard = Color(0xFFFFFFFF)
val GoldenYellowContainer = Color(0xFFFFD54A)
val OnGoldenYellowContainer = Color(0xFF251A00)
val FreshGreen = Color(0xFF356A3E)
val OnFreshGreen = Color(0xFFFFFFFF)
val FreshGreenContainer = Color(0xFFB8F0BD)
val OnFreshGreenContainer = Color(0xFF00210A)
val FryPaper = Color(0xFFFFFFFF)
val CounterWhite = Color(0xFFFFFFFF)
val WarmSurfaceVariant = Color(0xFFF5F5F5)
val Charcoal = Color(0xFF1C1B1A)
val MutedCharcoal = Color(0xFF686461)
val Outline = Color(0xFF8E8A87)
val OutlineVariant = Color(0xFFE0DEDC)

val DriveThruRedLight = Color(0xFFFFB3B3)
val OnDriveThruRedLight = Color(0xFF680013)
val DriveThruRedContainerDark = Color(0xFF9B001F)
val OnDriveThruRedContainerDark = Color(0xFFFFDAD8)
val GoldenMustardLight = Color(0xFFF1C21B)
val OnGoldenMustardLight = Color(0xFF3D2F00)
val GoldenYellowContainerDark = Color(0xFF584400)
val OnGoldenYellowContainerDark = Color(0xFFFFE16C)
val FreshGreenLight = Color(0xFF9CD59F)
val OnFreshGreenLight = Color(0xFF003914)
val FreshGreenContainerDark = Color(0xFF1B5229)
val OnFreshGreenContainerDark = Color(0xFFB8F0BD)
val NightCanvas = Color(0xFF1B1110)
val NightSurface = Color(0xFF241918)
val NightSurfaceVariant = Color(0xFF53433F)
val NightInk = Color(0xFFF2DFDA)
val NightMutedInk = Color(0xFFD8C2BC)
val NightOutline = Color(0xFFA98C85)
val NightOutlineVariant = Color(0xFF53433F)
