package com.example.settings.theme

import androidx.compose.ui.graphics.Color

// Light palette: warm neutrals with orange as the single visual accent.
val Orange = Color(0xFFFF8A00)
val OnOrange = Color(0xFF2B1200)
val OrangeContainer = Color(0xFFFFDBC8)
val OnOrangeContainer = Color(0xFF3A0B00)
val Cinnamon = Color(0xFF7D3F00)
val OnCinnamon = Color(0xFFFFFFFF)
val CinnamonContainer = Color(0xFFFFDDBE)
val OnCinnamonContainer = Color(0xFF2A1600)
val WarmGold = Color(0xFF765500)
val OnWarmGold = Color(0xFFFFFFFF)
val WarmGoldContainer = Color(0xFFFFE0A6)
val OnWarmGoldContainer = Color(0xFF271900)
val WarmCanvas = Color(0xFFFFF8F3)
val WarmSurface = Color(0xFFFFFDFC)
val WarmSurfaceVariant = Color(0xFFF3E6DC)
val WarmInk = Color(0xFF251B16)
val WarmMutedInk = Color(0xFF60544D)
val WarmOutline = Color(0xFF7D6F67)
val WarmOutlineVariant = Color(0xFFD9C9BE)

// Dark palette: the same orange identity on a deep coffee canvas.
val OrangeLight = Color(0xFFFFB477)
val OnOrangeLight = Color(0xFF4A1A00)
val DeepOrange = Color(0xFFA83D00)
val OnDeepOrange = Color(0xFFFFDBC8)
val CinnamonLight = Color(0xFFFFB77C)
val OnCinnamonLight = Color(0xFF4A2500)
val DeepCinnamon = Color(0xFF733A00)
val OnDeepCinnamon = Color(0xFFFFDCBC)
val WarmGoldLight = Color(0xFFE9C566)
val OnWarmGoldLight = Color(0xFF3D2D00)
val DeepGold = Color(0xFF5B4300)
val OnDeepGold = Color(0xFFFFE0A6)
val CoffeeNight = Color(0xFF1A100B)
val CoffeeSurface = Color(0xFF231713)
val CoffeeElevated = Color(0xFF33221B)
val CoffeeText = Color(0xFFFFEDE5)
val CoffeeMutedText = Color(0xFFD6C1B8)
val CoffeeOutline = Color(0xFFA99387)
val CoffeeOutlineVariant = Color(0xFF57443A)

val SettingsError = Color(0xFFBA1A1A)
val SettingsErrorContainer = Color(0xFFFFDAD6)
val SettingsOnErrorContainer = Color(0xFF410002)
val SettingsDarkError = Color(0xFFFFB4AB)
val SettingsDarkOnError = Color(0xFF690005)
val SettingsDarkErrorContainer = Color(0xFF93000A)
val SettingsDarkOnErrorContainer = Color(0xFFFFDAD6)
